server:
  port: 16115

spring:
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller

user-service:
  url: http://${USER_SERVICE_HOST:ts-user-service}:${USER_SERVICE_PORT:12342}