server:
  port: 12347

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local
  application:
    name: ts-contacts-service
  data:
    mongodb:
      host: ts-contacts-mongo
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller