server:
  port: 16113

spring:
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller

route-service:
  url: http://${ROUTE_SERVICE_HOST:ts-route-service}:${ROUTE_SERVICE_PORT:11178}