spring:
  application:
    name: ts-route-plan-service

# HTTP Server
server:
  port: 14578 # HTTP (Tomcat) port


swagger:
  controllerPackage: plan.controller

station-service:
  url: http://${STATION_SERVICE_HOST:ts-station-service}:${STATION_SERVICE_PORT:12345}

route-service:
  url: http://${ROUTE_SERVICE_HOST:ts-route-service}:${ROUTE_SERVICE_PORT:11178}

travel-service:
  url: http://${TRAVEL_SERVICE_HOST:ts-travel-service}:${TRAVEL_SERVICE_PORT:12346}

travel2-service:
  url: http://${TRAVEL2_SERVICE_HOST:ts-travel2-service}:${TRAVEL2_SERVICE_PORT:16346}