spring:
  application:
    name: ts-consign-service
  data:
    mongodb:
      host: ts-consign-mongo
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16111

swagger:
  controllerPackage: consign.controller

consign-price-service:
  url: http://${CONSIGN_PRICE_SERVICE_HOST:ts-consign-price-service}:${CONSIGN_PRICE_SERVICE_PORT:16110}